import type { Metadata } from "next";
import { Old_Standard_TT } from "next/font/google";
import "./globals.css";

const old_standard_tt = Old_Standard_TT({
  subsets: ["latin-ext"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={old_standard_tt.className}>{children}</body>
    </html>
  );
}
